name: chatting
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  chat_composer: ^1.0.1
  google_sign_in: ^5.3.0
  voice_message_package: ^0.0.66
  adaptive_action_sheet: ^2.0.1
  animated_bottom_navigation_bar: ^0.3.2
  animated_floating_buttons: ^0.0.2
  azlistview: ^2.0.0-nullsafety.0
  cloud_firestore: ^3.1.8
  cupertino_icons: ^1.0.2
  device_preview: ^1.0.0
  equatable: ^2.0.3
  file_picker: ^4.4.0
  firebase_auth: ^3.3.7
  firebase_core: ^1.12.0
  badges: ^2.0.2
  firebase_database: ^9.0.6
  firebase_storage: ^10.2.7
  url_launcher: ^6.0.20
  flutter_map: ^0.14.0
  any_link_preview: ^2.0.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_chat_ui: ^1.5.5
  random_color: ^1.0.5
  flutter_platform_widgets: ^1.20.0
  flutter_profile_picture: ^1.0.2
  flutter_smart_dialog: ^3.4.0+2
  flutter_svg: ^1.0.3
  geocoder: ^0.2.1
  geocoding: ^2.0.4
  geolocator: ^8.2.0
  getwidget: ^2.0.5
  google_maps_flutter: ^2.1.1
  hive: ^2.0.5
  cached_network_image: ^3.2.0
  hive_flutter: ^1.1.0
  intl_phone_number_input: ^0.7.0+2
  path_provider: ^2.0.9
  pinput: ^1.2.2
  provider: ^6.0.2
  scrollable_positioned_list: ^0.2.3
  shared_preferences: ^2.0.13
  sizer: ^2.0.15
  sticky_headers: ^0.2.0
  strings: ^0.2.2
  latlong2: ^0.8.1
  dio: ^4.0.6
  audioplayers: ^0.20.1
  just_audio: ^0.9.20
  intl: ^0.17.0
  comment_tree: ^0.3.0
  like_button: ^2.0.4
  image_picker: ^0.8.5
  contacts_service: ^0.6.3
  permission_handler: ^8.3.0
  flutter_dialogs: ^2.1.1
  detectable_text_field: ^2.0.3
  change_app_package_name: ^1.1.0



  


 


dev_dependencies:
  build_runner: ^2.1.7
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.2

flutter:

  uses-material-design: true

  assets:
    - assets/image/
    - assets/svg/
    - assets/audio/
