// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJJH0Uj7CvjefCOsbudF4d8RAeJHRZzg8',
    appId: '1:8456637305:android:6763741b17aace71167da8',
    messagingSenderId: '8456637305',
    projectId: 'chatterapp-8dfbf',
    storageBucket: 'chatterapp-8dfbf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkM9lQkI4TauJY9BuIhATCeRctdn4cb-k',
    appId: '1:8456637305:ios:1662ab30de35a9c3167da8',
    messagingSenderId: '8456637305',
    projectId: 'chatterapp-8dfbf',
    storageBucket: 'chatterapp-8dfbf.appspot.com',
    androidClientId: '8456637305-bdihkcuqujdu1s45mfb29s3bo8knqvdn.apps.googleusercontent.com',
    iosClientId: '8456637305-un21g1nrmcvgl59itdk8pbbkqasngrbs.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat',
  );
}
