// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTh0czkWaRQQAdOn0kwMZt2jsI63_Y52s',
    appId: '1:397110478415:web:5958ec75013bb01da08c3a',
    messagingSenderId: '397110478415',
    projectId: 'chat-cff54',
    authDomain: 'chat-cff54.firebaseapp.com',
    storageBucket: 'chat-cff54.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAa-jh47M4qXrKJNnwounRUSLYE6Uhehm8',
    appId: '1:397110478415:android:984d42629862c3cfa08c3a',
    messagingSenderId: '397110478415',
    projectId: 'chat-cff54',
    storageBucket: 'chat-cff54.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0OdjAHJrf_dCKokmz2E_ePXi979S_OPk',
    appId: '1:397110478415:ios:6f3fe79f3d63d682a08c3a',
    messagingSenderId: '397110478415',
    projectId: 'chat-cff54',
    storageBucket: 'chat-cff54.appspot.com',
    androidClientId: '397110478415-425melr1lh8in0l1u681c2fd7c45qv9l.apps.googleusercontent.com',
    iosClientId: '397110478415-f1dhmch2ijafpfhge6o62g8jjtbcb31n.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat',
  );
}
